<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ddBW92A' shared service.

return $this->privates['.service_locator.ddBW92A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'entreprise' => ['privates', '.errored..service_locator.ddBW92A.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator.ddBW92A": it references class "App\\Entity\\Entreprise" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'entityManager' => '?',
    'entreprise' => 'App\\Entity\\Entreprise',
    'manager' => '?',
    'serializer' => '?',
    'validator' => '?',
]);
