<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ati0_KT' shared service.

return $this->privates['.service_locator.ati0_KT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'compteRepository' => ['privates', 'App\\Repository\\CompteRepository', 'getCompteRepositoryService.php', true],
    'serialize' => ['services', 'serializer', 'getSerializerService', false],
], [
    'compteRepository' => 'App\\Repository\\CompteRepository',
    'serialize' => '?',
]);
