<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZxKJxjQ' shared service.

return $this->privates['.service_locator.ZxKJxjQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'profilRepository' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService.php', true],
    'serialize' => ['services', 'serializer', 'getSerializerService', false],
], [
    'profilRepository' => 'App\\Repository\\ProfilRepository',
    'serialize' => '?',
]);
