<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Lsbb24\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Lsbb24/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Lsbb24.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Lsbb24\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5Lsbb24\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5Lsbb24',
    'container.build_id' => 'a4a4b8f3',
    'container.build_time' => 1571931118,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Lsbb24');
